import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Connect Guide - App Store Connect & TestFlight
const connectGuideHtml = `
<h1>Mastering App Store Connect & TestFlight (2025)</h1>

<p>The technical submission process is often as tricky as the review itself. From configuring Bundle IDs to managing beta testers, this guide covers the essential technical steps to prepare your binary for a successful launch.</p>

<div class="alert-box info">
  <div class="alert-title">Before You Start</div>
  <p>Make sure you have an active Apple Developer Program membership ($99/year) and access to App Store Connect at <a href="https://appstoreconnect.apple.com" target="_blank">appstoreconnect.apple.com</a>.</p>
</div>

<hr />

<!-- Setting Up the App Record -->
<section id="setting-up">
<div class="section-header">
  <div class="section-header-icon blue">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
    </svg>
  </div>
  <h2>Setting Up the App Record</h2>
</div>

<p>Before you can even open Xcode, you must create the "shell" for your app in App Store Connect. This reserves your app name.</p>

<div class="checklist">
  <div class="checklist-item">
    <div class="checklist-number">1</div>
    <div class="checklist-content">
      <h4>Bundle ID Match</h4>
      <p>The <strong>Bundle ID</strong> in Connect must match the "Bundle Identifier" in your Xcode project settings exactly (e.g., <code>com.yourcompany.appname</code>).</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">2</div>
    <div class="checklist-content">
      <h4>SKU (Stock Keeping Unit)</h4>
      <p>This is a unique ID for your internal tracking (like an inventory number). It is <strong>not visible</strong> to users on the App Store.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">3</div>
    <div class="checklist-content">
      <h4>Primary Language</h4>
      <p>Choose carefully. If you set this to English, you can add Spanish later, but changing the "Primary" language is a complex process.</p>
    </div>
  </div>
</div>
</section>

<hr />

<!-- Uploading the Binary -->
<section id="uploading">
<div class="section-header">
  <div class="section-header-icon green">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path>
    </svg>
  </div>
  <h2>Uploading the Binary</h2>
</div>

<p>You cannot upload your app code through the web browser. You must use Apple's developer tools.</p>

<div class="feature-grid">
  <div class="feature-card">
    <h3>Method A: Xcode (Recommended)</h3>
    <p>Select "Generic iOS Device" as target, go to <strong>Product → Archive</strong>, then click "Distribute App" in the Organizer.</p>
  </div>

  <div class="feature-card">
    <h3>Method B: Transporter</h3>
    <p>A standalone macOS app. Good if your internet is unstable or if you are uploading a <code>.ipa</code> file generated by a CI/CD pipeline.</p>
  </div>
</div>
</section>

<hr />

<!-- TestFlight Strategy -->
<section id="testflight">
<span class="pre-header">Beta Testing</span>
<h2>TestFlight Strategy</h2>

<p>TestFlight is your beta testing environment. It helps you catch bugs before the reviewer does.</p>

<div class="dark-card">
  <div class="dark-card-grid">
    <div>
      <h4>Internal Testing</h4>
      <p><strong>Audience:</strong> Your team (Admins, Developers)</p>
      <p><strong>Speed:</strong> Builds are available almost immediately after processing</p>
      <p><strong>Limit:</strong> Up to 100 users</p>
    </div>
    <div>
      <h4>External Testing</h4>
      <p><strong>Audience:</strong> Public beta testers via email or public link</p>
      <p><strong>Review:</strong> Requires <strong>Beta App Review</strong> (usually 24 hours)</p>
      <p><strong>Pro Tip:</strong> Passing Beta Review often makes the final App Store review faster</p>
    </div>
  </div>
</div>
</section>

<hr />

<!-- Submission Prep -->
<section id="submission-prep">
<div class="section-header">
  <div class="section-header-icon yellow">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
    </svg>
  </div>
  <h2>Submission Prep</h2>
</div>

<div class="alert-box neutral">
  <div class="alert-title">The Export Compliance Question</div>
  <p>When you submit, Apple will ask: "Does your app use encryption?"</p>
  <p><strong>Yes:</strong> If you use HTTPS calls (which almost everyone does). You usually qualify for the "Standard Encryption" exemption.</p>
  <p><strong>No:</strong> Only if your app is completely local and uses no networking.</p>
  <p><em>Tip: Add the key <code>ITSAppUsesNonExemptEncryption</code> set to <code>NO</code> in your Info.plist to skip this dialog if you qualify.</em></p>
</div>
</section>

<hr />

<!-- Release Options -->
<section id="release-options">
<span class="pre-header">Going Live</span>
<h2>Release Options</h2>

<div class="timeline">
  <div class="timeline-item">
    <div class="timeline-dot blue"></div>
    <h4>Manual Release</h4>
    <p><strong>Best for Marketing.</strong> You get approved, but the app waits. You click "Release" when your press release goes live.</p>
  </div>

  <div class="timeline-item">
    <div class="timeline-dot blue"></div>
    <h4>Automatic Release</h4>
    <p><strong>Best for Bug Fixes.</strong> The app goes live the moment Apple approves it. Risky if you aren't monitoring.</p>
  </div>

  <div class="timeline-item">
    <div class="timeline-dot green"></div>
    <h4>Phased Release</h4>
    <p><strong>Pro Move.</strong> Releases the update to 1% of users on Day 1, 2% on Day 2, etc. If a crash is found, you can pause it before everyone updates.</p>
  </div>
</div>
</section>

<hr />

<!-- Conclusion -->
<section id="conclusion">
<h2>Next Steps</h2>

<p>Once your app is submitted, it enters the review queue. Monitor your email and the Resolution Center in App Store Connect for any feedback from Apple.</p>

<div class="alert-box info">
  <div class="alert-title">Pro Tip</div>
  <p>Submit early in the week. Reviews submitted Monday-Wednesday typically get faster turnaround than weekend submissions.</p>
</div>
</section>
`

// Rejection Guide - App Store Rejection Reasons & How to Fix Them
const rejectionGuideHtml = `
<h1>App Store Rejection Reasons & How to Fix Them (2025)</h1>

<p>Getting rejected from the App Store is frustrating, but it's not the end. This guide helps you understand common rejection reasons and how to address them effectively.</p>

<div class="alert-box warning">
  <div class="alert-title">Don't Panic</div>
  <p>A rejection is feedback, not a final verdict. Most rejections can be resolved with targeted fixes and a thoughtful response.</p>
</div>

<hr />

<!-- Understanding Rejection Messages -->
<section id="understanding-rejections">
<div class="section-header">
  <div class="section-header-icon red">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path>
    </svg>
  </div>
  <h2>Understanding Rejection Messages</h2>
</div>

<p>When Apple rejects your app, they provide a specific guideline number and explanation. Here's how to decode them:</p>
</section>

<hr />

<!-- Top Rejection Reasons -->
<section id="top-rejections">
<span class="pre-header">Common Issues</span>
<h2>Top Rejection Reasons</h2>

<div class="dark-card">
  <h3>Guideline 2.1 - App Completeness</h3>
  <p><strong>What it means:</strong> Your app contains placeholder content, crashes, or has incomplete features.</p>
  <div class="dark-card-grid" style="margin-top: 1rem;">
    <div>
      <h4>How to fix:</h4>
      <ul>
        <li>Remove all placeholder text and images</li>
        <li>Test every feature path thoroughly</li>
        <li>Ensure all links and buttons work</li>
        <li>Check on multiple device sizes</li>
      </ul>
    </div>
  </div>
</div>

<div class="checklist">
  <div class="checklist-item">
    <div class="checklist-number" style="background: #ff3b30;">2.3</div>
    <div class="checklist-content">
      <h4>Guideline 2.3 - Accurate Metadata</h4>
      <p><strong>What it means:</strong> Your screenshots, description, or preview don't match the actual app. <strong>Fix:</strong> Update screenshots to reflect current UI, remove features from description that aren't in the app.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number" style="background: #ff3b30;">4.2</div>
    <div class="checklist-content">
      <h4>Guideline 4.2 - Minimum Functionality</h4>
      <p><strong>What it means:</strong> Your app is too simple or could be a website instead. <strong>Fix:</strong> Add native iOS features (widgets, notifications, offline mode), improve the UX beyond what a website offers.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number" style="background: #ff3b30;">5.1.1</div>
    <div class="checklist-content">
      <h4>Guideline 5.1.1 - Data Collection and Storage</h4>
      <p><strong>What it means:</strong> You're collecting user data without proper disclosure. <strong>Fix:</strong> Add a privacy policy link, explain data collection, implement proper consent mechanisms.</p>
    </div>
  </div>
</div>
</section>

<hr />

<!-- The Appeals Process -->
<section id="appeals">
<div class="section-header">
  <div class="section-header-icon blue">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
    </svg>
  </div>
  <h2>The Appeals Process</h2>
</div>

<p>If you believe Apple made an error, you can appeal:</p>

<div class="timeline">
  <div class="timeline-item">
    <div class="timeline-dot blue"></div>
    <h4>1. Reply in Resolution Center</h4>
    <p>Provide clear reasoning for why your app should be approved.</p>
  </div>

  <div class="timeline-item">
    <div class="timeline-dot blue"></div>
    <h4>2. Be Specific</h4>
    <p>Reference the exact guideline and explain how your app complies.</p>
  </div>

  <div class="timeline-item">
    <div class="timeline-dot blue"></div>
    <h4>3. Provide Evidence</h4>
    <p>Include screenshots, documentation, and comparisons to similar approved apps.</p>
  </div>

  <div class="timeline-item">
    <div class="timeline-dot green"></div>
    <h4>4. Stay Professional</h4>
    <p>Emotional responses don't help. Keep it factual and polite.</p>
  </div>
</div>

<div class="alert-box neutral">
  <div class="alert-title">Pro Tip</div>
  <p>Before appealing, objectively review your app against the guideline. Sometimes fixing the issue is faster than arguing.</p>
</div>
</section>

<hr />

<!-- Resubmission Best Practices -->
<section id="resubmission">
<span class="pre-header">After Rejection</span>
<h2>Resubmission Best Practices</h2>

<div class="feature-grid">
  <div class="feature-card">
    <h3>What to Include</h3>
    <ul style="margin: 0; padding-left: 1.25rem;">
      <li>Acknowledge the specific issue</li>
      <li>Explain exactly what you changed</li>
      <li>Provide steps to verify the fix</li>
      <li>Include demo credentials if needed</li>
    </ul>
  </div>

  <div class="feature-card">
    <h3>Timeline Expectations</h3>
    <ul style="margin: 0; padding-left: 1.25rem;">
      <li>First review: 24-48 hours typically</li>
      <li>Resubmission: Often faster (12-24 hours)</li>
      <li>Appeals: 1-3 business days</li>
    </ul>
  </div>
</div>
</section>

<hr />

<!-- Prevention Checklist -->
<section id="prevention">
<h2>Prevention Checklist</h2>

<p>Before every submission, verify the following:</p>

<div class="checklist">
  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Test on real devices</h4>
      <p>Don't rely solely on the simulator. Test on physical devices.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Complete all metadata</h4>
      <p>Fill in every required field in App Store Connect.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Remove debug content</h4>
      <p>No placeholder text, test accounts, or debug features visible.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Verify IAP functionality</h4>
      <p>Test all in-app purchases in sandbox mode.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Check privacy policy</h4>
      <p>Ensure it's accessible and accurately describes data practices.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Test poor network</h4>
      <p>Verify app behavior under slow or no network conditions.</p>
    </div>
  </div>
</div>
</section>
`

// Legal Compliance Guide
const legalComplianceHtml = `
<h1>App Store Legal & Privacy Compliance Guide (2025)</h1>

<p>Legal compliance is one of the most complex areas of App Store review. This guide covers the essential requirements to keep your app compliant.</p>

<hr />

<!-- Privacy Requirements -->
<section id="privacy">
<div class="section-header">
  <div class="section-header-icon green">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
    </svg>
  </div>
  <h2>Privacy Requirements</h2>
</div>

<h3>Privacy Policy (Required)</h3>

<p>Every app that collects any user data must have a privacy policy. This includes:</p>

<ul>
  <li>Apps with user accounts</li>
  <li>Apps using analytics</li>
  <li>Apps with any network requests</li>
  <li>Apps accessing device sensors</li>
</ul>

<div class="alert-box warning">
  <div class="alert-title">No Privacy Policy = Automatic Rejection</div>
  <p>Apple requires a privacy policy link in App Store Connect. The link must be accessible and the policy must be clear.</p>
</div>

<h3>App Privacy Labels</h3>

<p>In App Store Connect, you must disclose:</p>

<div class="feature-grid">
  <div class="feature-card">
    <h3>Data Used to Track You</h3>
    <p>Advertising identifiers, cross-app tracking data</p>
  </div>

  <div class="feature-card">
    <h3>Data Linked to You</h3>
    <p>Email, name, payment info, user ID</p>
  </div>

  <div class="feature-card">
    <h3>Data Not Linked to You</h3>
    <p>Anonymous analytics, crash logs</p>
  </div>
</div>

<div class="alert-box info">
  <div class="alert-title">Be Accurate</div>
  <p>Apple may verify these claims during review. Inaccurate privacy labels can result in rejection.</p>
</div>
</section>

<hr />

<!-- Data Protection Laws -->
<section id="data-protection">
<span class="pre-header">Regional Compliance</span>
<h2>Data Protection Laws</h2>

<div class="dark-card">
  <div class="dark-card-grid">
    <div>
      <h4>GDPR (European Union)</h4>
      <p>If your app is available in the EU:</p>
      <ul>
        <li>Obtain explicit consent before collecting data</li>
        <li>Provide data export and deletion options</li>
        <li>Have a legal basis for processing</li>
        <li>Appoint a Data Protection Officer if required</li>
      </ul>
    </div>
    <div>
      <h4>CCPA (California)</h4>
      <p>If you have California users:</p>
      <ul>
        <li>Disclose data collection practices</li>
        <li>Provide opt-out for data selling</li>
        <li>Honor "Do Not Sell" requests</li>
      </ul>

      <h4 style="margin-top: 1.5rem;">COPPA (Children)</h4>
      <p>If your app targets children under 13:</p>
      <ul>
        <li>No behavioral advertising</li>
        <li>Parental consent required</li>
        <li>Limited data collection</li>
      </ul>
    </div>
  </div>
</div>
</section>

<hr />

<!-- In-App Purchase Rules -->
<section id="iap-rules">
<div class="section-header">
  <div class="section-header-icon blue">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"></path>
    </svg>
  </div>
  <h2>In-App Purchase Rules</h2>
</div>

<div class="feature-grid">
  <div class="feature-card">
    <h3>Must Use IAP</h3>
    <ul style="margin: 0; padding-left: 1.25rem;">
      <li>Digital content (ebooks, music, videos)</li>
      <li>Subscriptions to digital services</li>
      <li>Game currency and items</li>
      <li>Premium features</li>
    </ul>
  </div>

  <div class="feature-card">
    <h3>Cannot Use IAP</h3>
    <ul style="margin: 0; padding-left: 1.25rem;">
      <li>Physical goods and services</li>
      <li>Real-world service bookings</li>
      <li>Person-to-person payments</li>
    </ul>
  </div>
</div>

<h3>Subscription Requirements</h3>

<div class="table-wrapper">
  <table>
    <thead>
      <tr>
        <th>Requirement</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Clear Pricing</strong></td>
        <td>Show price and billing frequency prominently</td>
      </tr>
      <tr>
        <td><strong>Free Trial Terms</strong></td>
        <td>Disclose exactly when charges begin</td>
      </tr>
      <tr>
        <td><strong>Cancellation</strong></td>
        <td>Explain how to cancel the subscription</td>
      </tr>
      <tr>
        <td><strong>Auto-Renewal</strong></td>
        <td>Clearly state that subscription automatically renews</td>
      </tr>
    </tbody>
  </table>
</div>
</section>

<hr />

<!-- Content Regulations -->
<section id="content">
<span class="pre-header">Content Guidelines</span>
<h2>Content Regulations</h2>

<h3>Age Ratings</h3>

<p>Rate your app honestly:</p>

<div class="checklist">
  <div class="checklist-item">
    <div class="checklist-number" style="background: #34c759;">4+</div>
    <div class="checklist-content">
      <h4>No objectionable content</h4>
      <p>Suitable for all ages with no offensive material.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number" style="background: #007aff;">9+</div>
    <div class="checklist-content">
      <h4>Mild cartoon violence</h4>
      <p>Infrequent mild or fantasy violence.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number" style="background: #ff9500;">12+</div>
    <div class="checklist-content">
      <h4>Mild language, simulated gambling</h4>
      <p>Infrequent mild language and mature themes.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number" style="background: #ff3b30;">17+</div>
    <div class="checklist-content">
      <h4>Mature content, real gambling</h4>
      <p>Frequent intense violence, mature themes, real gambling.</p>
    </div>
  </div>
</div>

<h3>Prohibited Content</h3>

<div class="alert-box warning">
  <div class="alert-title">Never Include</div>
  <ul>
    <li>Illegal activities</li>
    <li>Discrimination or hate speech</li>
    <li>Realistic violence</li>
    <li>Pornography</li>
    <li>Unauthorized gambling</li>
  </ul>
</div>

<h3>User-Generated Content</h3>

<p>If your app allows UGC, you must:</p>

<ul>
  <li>Implement content moderation</li>
  <li>Provide reporting mechanism</li>
  <li>Block objectionable content</li>
  <li>Filter for minors if applicable</li>
</ul>
</section>

<hr />

<!-- Intellectual Property -->
<section id="ip">
<div class="section-header">
  <div class="section-header-icon yellow">
    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
    </svg>
  </div>
  <h2>Intellectual Property</h2>
</div>

<div class="feature-grid">
  <div class="feature-card">
    <h3>Trademark</h3>
    <ul style="margin: 0; padding-left: 1.25rem;">
      <li>Don't use Apple trademarks inappropriately</li>
      <li>Don't imply Apple endorsement</li>
      <li>Respect third-party trademarks</li>
    </ul>
  </div>

  <div class="feature-card">
    <h3>Copyright</h3>
    <ul style="margin: 0; padding-left: 1.25rem;">
      <li>Only use content you own or license</li>
      <li>Respond to DMCA takedowns</li>
      <li>Don't scrape copyrighted content</li>
    </ul>
  </div>
</div>
</section>

<hr />

<!-- Compliance Checklist -->
<section id="checklist">
<h2>Compliance Checklist</h2>

<div class="checklist">
  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Privacy policy published and linked</h4>
      <p>Both in App Store Connect and accessible within the app.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>App Privacy labels completed accurately</h4>
      <p>All data collection disclosed in App Store Connect.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>GDPR compliance (if applicable)</h4>
      <p>Consent mechanisms, data export, deletion requests.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>IAP used correctly for digital goods</h4>
      <p>No external payment links for digital content.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Age rating accurate</h4>
      <p>Content rating matches actual app content.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>Content moderation in place (if UGC)</h4>
      <p>Reporting, blocking, and filtering mechanisms.</p>
    </div>
  </div>

  <div class="checklist-item">
    <div class="checklist-number">✓</div>
    <div class="checklist-content">
      <h4>No trademark violations</h4>
      <p>Only using content you have rights to.</p>
    </div>
  </div>
</div>
</section>
`

async function updateAllArticles() {
  console.log('Updating all articles with rich HTML content...\n')

  const updates = [
    { slug: 'connect-guide', content: connectGuideHtml },
    { slug: 'rejection-guide', content: rejectionGuideHtml },
    { slug: 'legal-compliance', content: legalComplianceHtml },
  ]

  for (const update of updates) {
    try {
      const updated = await prisma.article.update({
        where: { slug: update.slug },
        data: { content: update.content },
      })

      console.log(`✓ Updated: ${updated.slug}`)
      console.log(`  Title: ${updated.title}`)
      console.log(`  Content length: ${updated.content.length} characters\n`)
    } catch (error) {
      console.error(`✗ Failed to update ${update.slug}:`, error)
    }
  }

  console.log('✓ All articles updated with rich HTML!')
}

updateAllArticles()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
